spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Taoxj/sc_properties/
          search-paths: config
          username:
          password:
      label: master

server:
  port: 1113